### ISSUE TITLE
Works on Raspberry Pi with latest v1.0.2 Node-RED

### ISSUE THREAD

**Issue by Humancell** [tek79/node-red-contrib-i2clcd-alt#1]
I wanted to write and thank you for creating this!  With the latest versions of Node-RED on Raspberry Pi (installed and upgraded via the script here: https://nodered.org/docs/getting-started/raspberrypi) I found that the older software you list in your README all broke with Node.js v10.

I teach a class, and we installed your code last night on numerous Raspberry Pi B 3+ running Raspbian and it worked perfectly!

Thank you!

**Comment by tek79** [comment]
Glad to hear it is working well. I am looking into moving this to NPM at some point for easier installation. Aside from getting this working under Armbian, my other motivation was to get something working under Node.js v10, as I have several v8 installations with LCD screens attached that will need updating soon.

**Comment by tek79** [comment]
Sorry, these are actually the latest versions of the dependencies. You should be okay up to Node 14.x, though I have not tested it. The NAN library, required by Sleep, which is one of my dependencies, is only supporting up to Node 14.x, according to their docs.
